# methods: 
#   cold_start: 2024-09-24/18-07-21 #2024-07-30/23-14-17 #2024-06-08/16-46-33
#   lasco: 2024-09-30/13-56-24 #2024-09-26/22-45-20 #2024-09-25/16-25-42 #16-15-44 #15-56-08 # #2024-07-31/10-59-53
#   UB97.5: 2024-09-30/17-00-39 #2024-09-30/13-56-24 #2024-09-26/22-45-20 #2024-07-31/10-59-53
#   LB2.5: 2024-09-30/17-00-39 #2024-09-30/13-56-24 #2024-09-26/22-45-20 #2024-07-31/10-59-53
#   silver: 2024-09-24/18-32-07 #2024-08-01/13-02-15 #2024-07-31/17-33-35
#   nearest_neighbor: 2024-09-24/18-07-21 #2024-07-30/23-14-17
#   nesterov: 2024-09-24/18-07-21 #2024-08-01/13-02-15 #2024-07-31/17-33-35
#   l2ws:  2024-08-01/14-23-33 #2024-07-31/13-51-16
#   l2ws10000: 2024-09-30/16-04-47
#   lm: 2024-08-01/15-33-20 #2024-07-31/14-56-28
#   lm10000: 2024-08-01/15-30-19
#   # conj_grad: 2024-06-11/14-56-59
#   lasco_one_step: 2024-09-30/17-00-39 #2024-09-25/16-25-42
# num_iters: 2000
# step_size_iters: 110

methods: 
  cold_start: 2024-09-24/18-07-21 #2024-07-30/23-14-17 #2024-06-08/16-46-33
  lasco: 2024-10-01/13-51-40 #2024-09-30/13-56-24 #2024-09-26/22-45-20 #2024-09-25/16-25-42 #16-15-44 #15-56-08 # #2024-07-31/10-59-53
  UB97.5: 2024-10-01/13-51-40 #2024-09-30/17-00-39 #2024-09-30/13-56-24 #2024-09-26/22-45-20 #2024-07-31/10-59-53
  LB2.5: 2024-10-01/13-51-40 #2024-09-30/17-00-39 #2024-09-30/13-56-24 #2024-09-26/22-45-20 #2024-07-31/10-59-53
  silver: 2024-09-24/18-32-07 #2024-08-01/13-02-15 #2024-07-31/17-33-35
  nearest_neighbor: 2024-09-24/18-07-21 #2024-07-30/23-14-17
  nesterov: 2024-09-24/18-07-21 #2024-08-01/13-02-15 #2024-07-31/17-33-35
  l2ws:  2024-08-01/14-23-33 #2024-07-31/13-51-16
  l2ws10000: 2024-09-30/16-04-47
  lm: 2024-08-01/15-33-20 #2024-07-31/14-56-28
  lm10000: 2024-08-01/15-30-19
  # conj_grad: 2024-06-11/14-56-59
  lasco_one_step: 2024-10-07/20-08-07 #2024-09-30/17-00-39 #2024-09-25/16-25-42
num_iters: 2000
step_size_iters: 110
