nn_cfg:
  lr: 1e-3
  method: adam
  batch_size: 5
  epochs: 100

data:
  datetime: ''

eval_every_x_epochs: 2
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
epochs_jit: 2

N_train: 10000
N_test: 10
num_samples_train: 10
num_samples_test: 10
# eval_batch_size_test: 50



plot_iterates: [0, 10, 20]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'


accuracies: [.1, .01, .001, .0001]
normalize_inputs: True

skip_startup: False

eval_unrolls: 1000
supervised: True
train_unrolls: 30
algo: 'lm'

# load_weights_datetime: '2023-08-28/16-14-46'
# nn_load_type: deterministic
# load_weights_datetime: '2024-01-07/13-07-24'
# nn_load_type: stochastic
# save_weights_flag: True

